/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package nl.creativeskills.cordovaPlugins;

public final class R {
    public static final class animator {
        public static final int info=0x7f040000;
    }
    public static final class attr {
    }
    public static final class color {
        public static final int busy_indicator=0x7f060003;
        public static final int button_normal=0x7f060004;
        public static final int button_pressed=0x7f060005;
        public static final int canvas=0x7f060000;
        public static final int page_indicator=0x7f060002;
        public static final int seek_progress=0x7f06000c;
        public static final int seek_thumb=0x7f06000b;
        public static final int text_border_focused=0x7f06000a;
        public static final int text_border_normal=0x7f060008;
        public static final int text_border_pressed=0x7f060009;
        public static final int text_normal=0x7f060006;
        public static final int text_pressed=0x7f060007;
        public static final int toolbar=0x7f060001;
    }
    public static final class dimen {
        /**  Default screen margins, per the Android Design guidelines. 

         Example customization of dimensions originally defined in res/values/dimens.xml
         (such as screen margins) for screens with more than 820dp of available width. This
         would include 7" and 10" devices in landscape (~960dp and ~1280dp respectively).
    
         */
        public static final int activity_horizontal_margin=0x7f070000;
        public static final int activity_vertical_margin=0x7f070001;
    }
    public static final class drawable {
        public static final int busy=0x7f020000;
        public static final int button=0x7f020001;
        public static final int darkdenim3=0x7f020002;
        public static final int ic_arrow_left=0x7f020003;
        public static final int ic_arrow_right=0x7f020004;
        public static final int ic_arrow_up=0x7f020005;
        public static final int ic_cancel=0x7f020006;
        public static final int ic_clipboard=0x7f020007;
        public static final int ic_dir=0x7f020008;
        public static final int ic_doc=0x7f020009;
        public static final int ic_launcher=0x7f02000a;
        public static final int ic_link=0x7f02000b;
        public static final int ic_list=0x7f02000c;
        public static final int ic_magnifying_glass=0x7f02000d;
        public static final int ic_reflow=0x7f02000e;
        public static final int ic_select=0x7f02000f;
        public static final int ic_strike=0x7f020010;
        public static final int ic_updir=0x7f020011;
        public static final int icon=0x7f020012;
        public static final int page_num=0x7f020013;
        public static final int search=0x7f020014;
        public static final int seek_progress=0x7f020015;
        public static final int seek_thumb=0x7f020016;
        public static final int tiled_background=0x7f020017;
    }
    public static final class id {
        public static final int closeBtn=0x7f0a0001;
        public static final int docNameText=0x7f0a0002;
        public static final int info=0x7f0a0003;
        public static final int lowerButtons=0x7f0a0000;
    }
    public static final class layout {
        public static final int buttons=0x7f030000;
        public static final int main=0x7f030001;
        public static final int textentry=0x7f030002;
    }
    public static final class string {
        public static final int app_name=0x7f080000;
        public static final int button_close=0x7f080015;
        public static final int cancel=0x7f080006;
        public static final int content_failure=0x7f080005;
        public static final int copy=0x7f080013;
        public static final int enter_password=0x7f08000c;
        public static final int link_control=0x7f08000f;
        public static final int no_further_occurences_found=0x7f080010;
        public static final int no_media_hint=0x7f080003;
        public static final int no_media_warning=0x7f080002;
        public static final int open_failed=0x7f080004;
        public static final int outline_title=0x7f08000b;
        public static final int picker_title=0x7f08000a;
        public static final int search=0x7f080012;
        public static final int search_backwards=0x7f080007;
        public static final int search_document=0x7f080009;
        public static final int search_forwards=0x7f080008;
        public static final int searching_=0x7f08000e;
        public static final int select=0x7f080011;
        public static final int strike_out=0x7f080014;
        public static final int text_not_found=0x7f08000d;
        public static final int version=0x7f080001;
    }
    public static final class style {
        /** 
        Base application theme, dependent on API level. This theme is replaced
        by AppBaseTheme from res/values-vXX/styles.xml on newer devices.
    

            Theme customizations available in newer API levels can go in
            res/values-vXX/styles.xml, while customizations related to
            backward-compatibility can go here.
        

        Base application theme for API 11+. This theme completely replaces
        AppBaseTheme from res/values/styles.xml on API 11+ devices.
    
 API 11 theme customizations can go here. 

        Base application theme for API 14+. This theme completely replaces
        AppBaseTheme from BOTH res/values/styles.xml and
        res/values-v11/styles.xml on API 14+ devices.
    
 API 14 theme customizations can go here. 
         */
        public static final int AppBaseTheme=0x7f090000;
        /**  Application theme. 
 All customizations that are NOT specific to a particular API-level can go here. 
         */
        public static final int AppTheme=0x7f090001;
    }
    public static final class xml {
        public static final int config=0x7f050000;
    }
}
